apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fuseki-docker
spec:
  selector:
    matchLabels:
      app: fuseki-docker
  serviceName: fuseki-docker
  replicas: 1
  template:
    metadata:
      labels:
        app: fuseki-docker
    spec:
      containers:
        - name: fuseki-docker
          image: docker.io/amannm/fuseki-docker
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 512M
          ports:
            - name: fuseki
              protocol: TCP
              containerPort: 3030
          volumeMounts:
            - name: dataset
              mountPath: /dataset
  volumeClaimTemplates:
    - metadata:
        name: dataset
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: fuseki-docker
  labels:
    app: fuseki-docker
spec:
  selector:
    app: fuseki-docker
  clusterIP: None
  ports:
    - name: fuseki
      protocol: TCP
      port: 3030